/**
 * Maps alternate/duplicate keyword paths to a single canonical route.
 * Wired into next.config.ts `redirects()` as permanent (301) redirects, so
 * stray inbound links or accidentally-indexed variants consolidate onto one
 * URL instead of splitting ranking signal across near-duplicate pages.
 */
export const CANONICAL_ALIASES: Record<string, string> = {
  "/cards/masti/zhezly-znachenie": "/cards/masti/zhezly",
  "/cards/masti/mechi-znachenie": "/cards/masti/mechi",
  "/cards/masti/kubki-znachenie": "/cards/masti/kubki",
  "/cards/masti/pentakli-znachenie": "/cards/masti/pentakli",
  "/cards/masti/zhezly-taro": "/cards/masti/zhezly",
  "/cards/masti/mechi-taro": "/cards/masti/mechi",
  "/cards/masti/kubki-taro": "/cards/masti/kubki",
  "/cards/masti/pentakli-taro": "/cards/masti/pentakli",
  "/taro-online": "/taro",
  "/taro-onlayn": "/taro",
  "/gadanie-taro-online": "/taro",
  "/karty-taro": "/cards",
  "/znachenie-kart-taro": "/cards",
  "/starshie-arkany": "/cards/starshie-arkany",
  "/arkany-taro": "/cards/starshie-arkany",
  "/natalnaya-karta-online": "/natalnaya-karta",
  "/natalnaya-karta-onlayn": "/natalnaya-karta",
  "/raschet-natalnoy-karty": "/natalnaya-karta",
  "/natalnaya-karta-po-date-rozhdeniya": "/natalnaya-karta",
  "/natalnaya-karta-besplatno": "/natalnaya-karta",
  "/goroskop-rozhdeniya": "/natalnaya-karta",
  "/matrica-sudby": "/numerology/destiny-matrix",
  "/matrica-sudby-online": "/numerology/destiny-matrix",
  "/matrica-sudby-onlayn": "/numerology/destiny-matrix",
  "/matrica-sudby-po-date-rozhdeniya": "/numerology/destiny-matrix",
  "/matrica-sudby-besplatno": "/numerology/destiny-matrix",
  "/raschet-matricy-sudby": "/numerology/destiny-matrix",
  "/matrix-destiny": "/numerology/destiny-matrix",
  "/astrology": "/natalnaya-karta",
  "/bodigraf": "/dizayn-cheloveka/rasschitat",
  "/bodigraf-onlayn": "/dizayn-cheloveka/rasschitat",
  "/bodygraph": "/dizayn-cheloveka/rasschitat",
  "/taro-po-foto": "/photo-rasklad",
  "/rasshifrovka-taro-po-foto": "/photo-rasklad",
  "/aura-po-foto": "/aura",
  "/cvet-aury": "/aura/cveta",
  "/khiromantiya": "/gadanie-po-ladoni",
  "/chiromantiya": "/gadanie-po-ladoni",
  "/khiromantiya-online": "/gadanie-po-ladoni",
  "/khiromantiya-onlayn": "/gadanie-po-ladoni",
  "/ladon": "/gadanie-po-ladoni",
  "/gadanie-po-ruke": "/gadanie-po-ladoni",
  "/gadanie-po-ladoni-online": "/gadanie-po-ladoni",
  "/gadanie-po-ladoni-onlayn": "/gadanie-po-ladoni",
  "/gadanie-po-ladoni-po-foto": "/gadanie-po-ladoni/po-foto",
  "/khiromantiya-po-foto": "/gadanie-po-ladoni/po-foto",
  "/gadanie-po-ladoni-besplatno": "/gadanie-po-ladoni/besplatno",
  "/levaya-ladon": "/gadanie-po-ladoni/levaya",
  "/pravaya-ladon": "/gadanie-po-ladoni/pravaya",
  "/liniya-zhizni": "/gadanie-po-ladoni/linii/zhizni",
  "/linia-zhizni": "/gadanie-po-ladoni/linii/zhizni",
  "/liniya-sudby": "/gadanie-po-ladoni/linii/sudby",
  "/linia-sudby": "/gadanie-po-ladoni/linii/sudby",
  "/liniya-serdca": "/gadanie-po-ladoni/linii/serdca",
  "/liniya-uma": "/gadanie-po-ladoni/linii/uma",
  "/kholm-venery": "/gadanie-po-ladoni/kholmy/venery",
  "/rasklady/chto-chuvstvuet-ona": "/rasklady/chto-ona-chuvstvuet",
  "/karta-dnya": "/gadanie/karta-dnya",
  "/karta-dnya-taro": "/gadanie/karta-dnya",
  "/gadanie-besplatno": "/gadanie/besplatno",
  "/gadanie-online-besplatno": "/gadanie/besplatno",
  "/goroskop": "/goroskop-na-segodnya",
  "/goroskop-online": "/goroskop-na-segodnya",
  "/goroskop-na-segodnya-besplatno": "/goroskop-na-segodnya",
  "/chislo-sudby": "/numerology/chislo-sudby",
  "/chislo-zhiznennogo-puti": "/numerology/chislo-sudby",
  "/chislo-sudby-po-date-rozhdeniya": "/numerology/chislo-sudby",
  "/gadanie-po-foto": "/photo-rasklad",
  "/rasklad-na-otnosheniya": "/rasklady/lyubov",
  "/lenormand-na-lyubov": "/lenormand/na-lyubov",
  "/runy-na-lyubov": "/runy/na-lyubov",
  "/gadanie-na-runakh-lyubov": "/runy/na-lyubov",
  "/sovmestimost-po-date": "/numerology/compatibility",
  "/sinastriya": "/natalnaya-karta/sovmestimost",
  "/sinastria": "/natalnaya-karta/sovmestimost",
  "/natal-ili-matrica-sudby": "/natal-ili-matrica",
  "/voskhodyashchiy": "/voskhodyashchiy-znak",
  "/ascendent": "/voskhodyashchiy-znak",
  "/astsendent": "/voskhodyashchiy-znak",
  "/lichnyy-god": "/numerology/lichnyy-god",
  "/lichniy-god": "/numerology/lichnyy-god",
  "/chislo-dushi": "/numerology/chislo-dushi",
  "/karmicheskiy-khvost": "/numerology/karmicheskiy-khvost",
  "/kanal-deneg": "/numerology/kanal-deneg",
  "/rasschitat-numerologiyu": "/numerology/rasschitat",
  "/numerologiya-rasschitat": "/numerology/rasschitat",
  "/gadanie-na-lyubov": "/gadanie/na-lyubov",
  "/gadanie-na-budushchee": "/gadanie/na-budushchee",
  "/gadanie-na-budushhee": "/gadanie/na-budushchee",
  "/rasklad-na-tri-karty": "/taro/tri-karty",
  "/rasklad-na-3-karty": "/taro/tri-karty",
  "/tri-karty-taro": "/taro/tri-karty",
  "/keltskiy-krest": "/rasklad/keltskij-krest",
  "/keltskij-krest": "/rasklad/keltskij-krest",
  "/gadanie-na-kartakh": "/taro",
  "/gadanie-na-kartah": "/taro",
  "/lenormand-da-net": "/lenormand/da-net",
  "/lenormand-na-rabotu": "/lenormand/na-rabotu",
  "/runy-na-rabotu": "/runy/na-rabotu",
  "/runy-na-dengi": "/runy/na-dengi",
  "/mladshie-arkany": "/cards/mladshie-arkany",
  "/aura-besplatno": "/aura/besplatno",
  "/proyektor-i-manifestor": "/dizayn-cheloveka/sovmestimost/manifestor-i-proektor",
  "/proektor-i-manifestor": "/dizayn-cheloveka/sovmestimost/manifestor-i-proektor",
  "/dizayn-cheloveka/sovmestimost/proektor-i-manifestor":
    "/dizayn-cheloveka/sovmestimost/manifestor-i-proektor",
  "/dizayn-cheloveka/sovmestimost/proyektor-i-manifestor":
    "/dizayn-cheloveka/sovmestimost/manifestor-i-proektor",
};

export function resolveCanonicalPath(path: string): string {
  return CANONICAL_ALIASES[path] ?? path;
}

export function getCanonicalRedirects(): { source: string; destination: string; permanent: boolean }[] {
  return Object.entries(CANONICAL_ALIASES).map(([source, destination]) => ({
    source,
    destination,
    permanent: true,
  }));
}
