import assert from 'node:assert/strict';
import { migrate } from '../../../db/client.js';
import { migrateUp, ensureCriticalColumns } from '../../../db/migrate-runner.js';
import { upsertUser } from '../../../db/repos.js';
import { presentReadingToTelegram, handleReadingPagerCallback } from '../present.js';
import type { Context } from 'grammy';
migrate(); migrateUp(); ensureCriticalColumns();
const uid = 990109;
upsertUser({ telegramUserId: uid, chatId: uid, firstName: 'Test' });
const messages: Array<{text:string,opts:any}> = [];
const ctx = { from:{id:uid}, reply:async(text:string,opts:any)=>{messages.push({text,opts});return {message_id:messages.length,chat:{id:uid}};} } as unknown as Context;
await presentReadingToTelegram(ctx,{reading:'Прошлое: REPORT_A.\n\nБудущее: NEXT_A.',sessionId:'session-a'});
const a = messages[0]!;
const next = a.opts.reply_markup.inline_keyboard.flat().find((b:any)=>b.text==='›').callback_data;
await presentReadingToTelegram(ctx,{reading:'Прошлое: REPORT_B.\n\nБудущее: NEXT_B.',sessionId:'session-b'});
let edited='';
await handleReadingPagerCallback({from:{id:uid},callbackQuery:{message:{message_id:1,chat:{id:uid}}},answerCallbackQuery:async()=>{},editMessageText:async(text:string)=>{edited=text;}} as unknown as Context,next);
assert.match(edited,/NEXT_A/,'A callback must retain A after navigation and another reading');
assert.doesNotMatch(edited,/NEXT_B/);
const plain:string[]=[];
await presentReadingToTelegram({from:{id:uid},reply:async(text:string,opts:any)=>{if(opts?.parse_mode==='HTML')throw Error('bad HTML');plain.push(text);return {message_id:7,chat:{id:uid}};}} as unknown as Context,{reading:('Совет карт: **Текст & смысл**.\n\n').repeat(600)});
assert.ok(plain.length>1);
assert.ok(plain.every(t=>t.length<=4096 && !/<\/?(?:b|i)>|&amp;/.test(t)),'plain fallback chunks are valid Telegram text');
console.log('reading delivery regressions PASS');
