ALTER TABLE hd_reports
  ADD COLUMN IF NOT EXISTS cost_rub NUMERIC(12, 4) NULL;
ALTER TABLE hd_reports
  ADD COLUMN IF NOT EXISTS llm_calls INTEGER NULL;
ALTER TABLE hd_reports
  ADD COLUMN IF NOT EXISTS token_usage JSONB NULL;
