-- Zovus Pro: idempotent client questions on delivery dialogs.
-- client_msg_id is generated by the /r/[token] page per composed question;
-- retries reuse it, so double-submit cannot consume quota or charge twice.
-- Rollback: DROP INDEX IF EXISTS pro.pro_thread_messages_client_msg_uniq;
--           ALTER TABLE pro.thread_messages DROP COLUMN IF EXISTS client_msg_id;

BEGIN;

DO $$
BEGIN
  IF to_regclass('pro.thread_messages') IS NULL THEN
    RAISE NOTICE 'pro.thread_messages missing — skip client_msg_id';
    RETURN;
  END IF;

  ALTER TABLE pro.thread_messages
    ADD COLUMN IF NOT EXISTS client_msg_id TEXT;

  EXECUTE 'CREATE UNIQUE INDEX IF NOT EXISTS pro_thread_messages_client_msg_uniq
    ON pro.thread_messages (thread_id, client_msg_id)
    WHERE client_msg_id IS NOT NULL';
END $$;

COMMIT;
