import type { SpreadSymbol } from "./types";

/** Classic 36-card Petit Lenormand — Russian names used across Zovus. */
export const LENORMAND_SYMBOLS: SpreadSymbol[] = [
  { id: 1, name: "Всадник", slug: "rider", meaning: "Новости, послание, быстрое движение" },
  { id: 2, name: "Клевер", slug: "clover", meaning: "Удача, шанс, лёгкость" },
  { id: 3, name: "Корабль", slug: "ship", meaning: "Путь, дистанция, перемены" },
  { id: 4, name: "Дом", slug: "house", meaning: "Семья, быт, стабильность" },
  { id: 5, name: "Дерево", slug: "tree", meaning: "Здоровье, рост, корни" },
  { id: 6, name: "Тучи", slug: "clouds", meaning: "Неясность, сомнение, тревога" },
  { id: 7, name: "Змея", slug: "snake", meaning: "Хитрость, интрига, искушение" },
  { id: 8, name: "Гроб", slug: "coffin", meaning: "Завершение, пауза, отпускание" },
  { id: 9, name: "Букет", slug: "bouquet", meaning: "Радость, подарок, красота" },
  { id: 10, name: "Коса", slug: "scythe", meaning: "Резкий поворот, разрыв, решение" },
  { id: 11, name: "Метла", slug: "whip", meaning: "Конфликт, повтор, давление" },
  { id: 12, name: "Птицы", slug: "birds", meaning: "Разговор, сплетни, тревожные мысли" },
  { id: 13, name: "Ребёнок", slug: "child", meaning: "Начало, наивность, что-то маленькое" },
  { id: 14, name: "Лиса", slug: "fox", meaning: "Осторожность, хитрость, самостоятельность" },
  { id: 15, name: "Медведь", slug: "bear", meaning: "Сила, начальник, защита" },
  { id: 16, name: "Звёзды", slug: "stars", meaning: "Надежда, вдохновение, ясность" },
  { id: 17, name: "Аист", slug: "stork", meaning: "Перемены, переезд, обновление" },
  { id: 18, name: "Собака", slug: "dog", meaning: "Друг, верность, поддержка" },
  { id: 19, name: "Башня", slug: "tower", meaning: "Одиночество, границы, официальность" },
  { id: 20, name: "Сад", slug: "garden", meaning: "Общество, событие, публичность" },
  { id: 21, name: "Гора", slug: "mountain", meaning: "Препятствие, задержка, испытание" },
  { id: 22, name: "Дорога", slug: "crossroads", meaning: "Выбор, путь, альтернатива" },
  { id: 23, name: "Мыши", slug: "mice", meaning: "Потери, стресс, мелкие проблемы" },
  { id: 24, name: "Сердце", slug: "heart", meaning: "Любовь, чувства, тепло" },
  { id: 25, name: "Кольцо", slug: "ring", meaning: "Союз, договор, цикл" },
  { id: 26, name: "Книга", slug: "book", meaning: "Тайна, знание, скрытое" },
  { id: 27, name: "Письмо", slug: "letter", meaning: "Документ, сообщение, новость" },
  { id: 28, name: "Мужчина", slug: "man", meaning: "Мужчина, активная энергия" },
  { id: 29, name: "Женщина", slug: "woman", meaning: "Женщина, принимающая энергия" },
  { id: 30, name: "Лилия", slug: "lily", meaning: "Покой, зрелость, чистота" },
  { id: 31, name: "Солнце", slug: "sun", meaning: "Успех, радость, ясность" },
  { id: 32, name: "Луна", slug: "moon", meaning: "Интуиция, сны, неопределённость" },
  { id: 33, name: "Ключ", slug: "key", meaning: "Решение, доступ, открытие" },
  { id: 34, name: "Рыбы", slug: "fish", meaning: "Деньги, изобилие, поток" },
  { id: 35, name: "Якорь", slug: "anchor", meaning: "Стабильность, работа, устойчивость" },
  { id: 36, name: "Крест", slug: "cross", meaning: "Судьба, испытание, глубокий урок" },
];

export const LENORMAND_POSITIONS = [
  "Основа",
  "Развитие",
  "Ядро",
  "Исход",
  "Ключ",
] as const;
