"use client";
import type { getFirstExperienceAnalytics } from "@/lib/first-experience-analytics";
export default function FirstExperienceMetrics({data}:{data:Awaited<ReturnType<typeof getFirstExperienceAnalytics>>|{unavailable:true}|undefined}) {
  if(!data)return null;
  if("unavailable" in data)return <p className="mt-6 text-white/60">Данные первого опыта временно недоступны.</p>;
  const labels:Record<string,string>={bonus_granted:"Начислен стартовый бонус",bonus_spent:"Использован бонус",bonus_refunded:"Возврат бонуса",first_result:"Первый результат",continuation_shown:"Показ продолжения",continuation_selected:"Выбор продолжения",insight_saved:"Сохранён вывод",step_saved:"Выбран шаг",changes_saved:"Отмечены изменения",payment_started:"Начало оплаты",first_topup:"Первое пополнение",repeat_topup:"Повторное пополнение"};
  const pct=(n:number|null)=>n===null?"Нет данных":`${(100*n).toFixed(1)}%`;
  return <section className="glass-panel mt-8 p-4 sm:p-6"><h2 className="font-display text-xl text-white">Первый опыт и возвращение</h2><p className="my-3 text-sm text-white/60">{data.definitions.firstPayment}</p>{data.cohorts.length?<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{["Регистрация (UTC)","Бонус","Аккаунты","Первый платёж / 7 дней","Первый платёж / 30 дней","Повторное пополнение"].map(t=><th key={t} className="p-2 font-normal text-white/60">{t}</th>)}</tr></thead><tbody>{data.cohorts.map(r=><tr key={`${r.day}:${r.version}`}><td className="p-2">{r.day}</td><td className="p-2">{r.version}</td><td className="p-2">{r.users}</td><td className="p-2">{pct(r.firstPayment7)} ({r.eligible7} созревших)</td><td className="p-2">{pct(r.firstPayment30)} ({r.eligible30} созревших)</td><td className="p-2">{pct(r.repeatPayment)}</td></tr>)}</tbody></table></div>:<p className="text-white/60">Пока нет данных о когортах.</p>}<div className="my-4 grid gap-2 sm:grid-cols-2">{data.events.length?data.events.map(item=><p className="text-sm text-white/70" key={item.event}>{labels[item.event]??item.event}: {item.count}</p>):<p className="text-white/60">События ещё не собраны.</p>}</div><p className="mt-4 text-sm text-white/65">{data.definitions.repeatPayment}</p><p className="mt-4 text-sm">Затраты на бесплатные генерации: {data.freeGenerationCost.totalRub===null?"полные данные отсутствуют":`${data.freeGenerationCost.totalRub.toFixed(2)} ₽`}. Учтённая часть: {data.freeGenerationCost.knownRub===null?"нет данных":`${data.freeGenerationCost.knownRub.toFixed(2)} ₽`}. Без данных о стоимости: {data.freeGenerationCost.untracked}.</p><p className="mt-2 text-xs text-white/50">{data.definitions.freeCost}</p></section>;
}
