/**
 * Hand-computed golden vectors for zovus-matrix-22-v1 (digit-sum, 22 stays).
 * Sources are listed per row. Values were not generated by destinyMatrix().
 */
export type MatrixGoldenExpected = {
  a: number;
  b: number;
  c: number;
  g: number;
  x: number;
  talents: number;
  love: number;
  money: number;
  sky: number;
  earth: number;
  paternal: number;
  maternal: number;
  tailTip: number;
};

export type MatrixGoldenVector = {
  birthDate: string;
  source: string;
  expected: MatrixGoldenExpected;
};

export const MATRIX_GOLDEN_VECTORS: MatrixGoldenVector[] = [
  {
    birthDate: "1990-08-15",
    source: "matrisa-sudbi.ru 15.08.1990 — A15 B8 C19 D6 X12",
    expected: {
      a: 15, b: 8, c: 19, g: 6, x: 12,
      talents: 5, love: 9, money: 4, sky: 20, earth: 18,
      paternal: 7, maternal: 9, tailTip: 6,
    },
  },
  {
    birthDate: "1984-09-07",
    source: "matrica-sudbyy.ru 7.09.1984 — A7 B9 C22 D11 X13",
    expected: {
      a: 7, b: 9, c: 22, g: 11, x: 13,
      talents: 16, love: 20, money: 8, sky: 22, earth: 6,
      paternal: 6, maternal: 4, tailTip: 17,
    },
  },
  {
    birthDate: "2000-01-01",
    source: "boundary year 2000; day/month 1; C=2",
    expected: {
      a: 1, b: 1, c: 2, g: 4, x: 8,
      talents: 2, love: 9, money: 10, sky: 9, earth: 12,
      paternal: 6, maternal: 3, tailTip: 16,
    },
  },
  {
    birthDate: "1999-12-31",
    source: "day 31→4; month 12; year 28→10",
    expected: {
      a: 4, b: 12, c: 10, g: 8, x: 7,
      talents: 16, love: 11, money: 17, sky: 19, earth: 15,
      paternal: 18, maternal: 22, tailTip: 5,
    },
  },
  {
    birthDate: "2000-02-29",
    source: "leap day 29→11",
    expected: {
      a: 11, b: 2, c: 2, g: 15, x: 3,
      talents: 13, love: 14, money: 5, sky: 5, earth: 18,
      paternal: 17, maternal: 4, tailTip: 6,
    },
  },
  {
    birthDate: "1992-02-29",
    source: "leap day + year 21",
    expected: {
      a: 11, b: 2, c: 21, g: 7, x: 5,
      talents: 13, love: 16, money: 8, sky: 7, earth: 12,
      paternal: 10, maternal: 5, tailTip: 19,
    },
  },
  {
    birthDate: "1991-11-22",
    source: "day 22 stays; month 11; year 20",
    expected: {
      a: 22, b: 11, c: 20, g: 8, x: 7,
      talents: 6, love: 11, money: 9, sky: 18, earth: 15,
      paternal: 10, maternal: 4, tailTip: 5,
    },
  },
  {
    birthDate: "1988-10-10",
    source: "repeated 10; year 26→8",
    expected: {
      a: 10, b: 10, c: 8, g: 10, x: 11,
      talents: 20, love: 21, money: 19, sky: 21, earth: 21,
      paternal: 18, maternal: 18, tailTip: 4,
    },
  },
  {
    birthDate: "1975-03-25",
    source: "day 25→7; year 22",
    expected: {
      a: 7, b: 3, c: 22, g: 5, x: 10,
      talents: 10, love: 17, money: 5, sky: 13, earth: 15,
      paternal: 9, maternal: 7, tailTip: 20,
    },
  },
  {
    birthDate: "2010-06-06",
    source: "repeated 6; year 3",
    expected: {
      a: 6, b: 6, c: 3, g: 15, x: 3,
      talents: 12, love: 9, money: 6, sky: 9, earth: 18,
      paternal: 18, maternal: 9, tailTip: 6,
    },
  },
  {
    birthDate: "1966-07-07",
    source: "repeated 7; year 22; 45→9 center",
    expected: {
      a: 7, b: 7, c: 22, g: 9, x: 9,
      talents: 14, love: 16, money: 4, sky: 16, earth: 18,
      paternal: 4, maternal: 11, tailTip: 9,
    },
  },
  {
    birthDate: "2020-12-12",
    source: "month 12; year 4; 24→6 talents",
    expected: {
      a: 12, b: 12, c: 4, g: 10, x: 11,
      talents: 6, love: 5, money: 15, sky: 5, earth: 21,
      paternal: 14, maternal: 16, tailTip: 4,
    },
  },
  {
    birthDate: "1980-04-23",
    source: "day 23→5; year 18",
    expected: {
      a: 5, b: 4, c: 18, g: 9, x: 9,
      talents: 9, love: 14, money: 9, sky: 13, earth: 18,
      paternal: 9, maternal: 22, tailTip: 9,
    },
  },
  {
    birthDate: "1955-05-05",
    source: "repeated 5; year 20",
    expected: {
      a: 5, b: 5, c: 20, g: 3, x: 6,
      talents: 10, love: 11, money: 8, sky: 11, earth: 9,
      paternal: 5, maternal: 7, tailTip: 12,
    },
  },
  {
    birthDate: "2001-01-22",
    source: "day 22 stays; year 3",
    expected: {
      a: 22, b: 1, c: 3, g: 8, x: 7,
      talents: 5, love: 11, money: 10, sky: 8, earth: 15,
      paternal: 11, maternal: 4, tailTip: 5,
    },
  },
  {
    birthDate: "1995-08-08",
    source: "repeated 8; year 24→6; 44→8 center",
    expected: {
      a: 8, b: 8, c: 6, g: 22, x: 8,
      talents: 16, love: 16, money: 14, sky: 16, earth: 3,
      paternal: 10, maternal: 14, tailTip: 7,
    },
  },
  {
    birthDate: "1987-02-14",
    source: "year 25→7",
    expected: {
      a: 14, b: 2, c: 7, g: 5, x: 10,
      talents: 16, love: 6, money: 17, sky: 12, earth: 15,
      paternal: 12, maternal: 9, tailTip: 20,
    },
  },
  {
    birthDate: "1970-01-01",
    source: "year 17",
    expected: {
      a: 1, b: 1, c: 17, g: 19, x: 11,
      talents: 2, love: 12, money: 10, sky: 12, earth: 3,
      paternal: 9, maternal: 18, tailTip: 22,
    },
  },
  {
    birthDate: "2003-03-03",
    source: "repeated 3; year 5; center 22",
    expected: {
      a: 3, b: 3, c: 5, g: 11, x: 22,
      talents: 6, love: 7, money: 9, sky: 7, earth: 6,
      paternal: 16, maternal: 8, tailTip: 17,
    },
  },
  {
    birthDate: "2012-12-21",
    source: "month 12; year 5",
    expected: {
      a: 21, b: 12, c: 5, g: 11, x: 13,
      talents: 6, love: 7, money: 18, sky: 7, earth: 6,
      paternal: 16, maternal: 17, tailTip: 17,
    },
  },
  {
    birthDate: "1922-11-11",
    source: "repeated 11; year 14",
    expected: {
      a: 11, b: 11, c: 14, g: 9, x: 9,
      talents: 22, love: 20, money: 5, sky: 20, earth: 18,
      paternal: 5, maternal: 7, tailTip: 9,
    },
  },
];
