import assert from 'node:assert/strict';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
process.env.BOT_DATA_DIR = mkdtempSync(join(tmpdir(), 'zovus-retention-'));
process.env.TELEGRAM_BOT_TOKEN = '123456:offline';
const { getDb, migrate } = await import('../client.js');
const { migrateUp, ensureCriticalColumns } = await import('../migrate-runner.js');
const { upsertUser } = await import('../repos.js');
const { pendingOperation } = await import('../../domain/paid-operation.js');
const { purgeOperationalHistory } = await import('../retention.js');
migrate(); migrateUp(); ensureCriticalColumns();
const db = getDb(), tid = 7611001;
upsertUser({ telegramUserId: tid, chatId: tid, firstName: 'Retention' });
const op = pendingOperation(tid, 'spread', { question: 'Unresolved paid result must survive cleanup' });
db.prepare("UPDATE bot_paid_operations SET created_at='2020-01-01',updated_at='2020-01-01' WHERE id=?").run(op.id);
db.prepare("INSERT INTO bot_events(name,telegram_user_id,payload,created_at) VALUES('old',?,'{}','2020-01-01'),('recent',?,'{}',?)").run(tid,tid,new Date().toISOString());
db.prepare("INSERT INTO bot_day_cards(telegram_user_id,day,card,text,created_at) VALUES(?,'2020-01-01','{}','private','2020-01-01')").run(tid);
assert.equal(purgeOperationalHistory(), 2);
assert.equal((db.prepare('SELECT count(*) AS n FROM bot_events').get() as {n:number}).n, 1);
assert(db.prepare('SELECT id FROM bot_paid_operations WHERE id=?').get(op.id));
assert.equal(purgeOperationalHistory(),0, 'repeat cleanup is idempotent');
console.log('operational retention PASS');
