-- Deprecated entrypoint — use the versioned migration runner instead.
--
-- Fresh DB (Docker): src/lib/schema.sql via docker-compose init
-- All environments:  npm run migrate   (scripts/migrate.mjs + scripts/migrations/*.sql)
-- Status:             npm run migrate:status
