import { DEFAULT_RUNE_COSTS } from "@/lib/rune-costs";

/** Single source of truth for fixed session prices (runes). */
export const PRICING = {
  /** Полная расшифровка матрицы судьбы у Эвелины (≈300 ₽). */
  NUMEROLOGY_SESSION: DEFAULT_RUNE_COSTS.NUMEROLOGY_SESSION,
  MATRIX_SUBJECT_REPORT: DEFAULT_RUNE_COSTS.MATRIX_SUBJECT_REPORT,
  CHILD_MATRIX_REPORT: DEFAULT_RUNE_COSTS.CHILD_MATRIX_REPORT,
  MATRIX_PAIR_REPORT: DEFAULT_RUNE_COSTS.MATRIX_PAIR_REPORT,
  MATRIX_YEAR_FORECAST: DEFAULT_RUNE_COSTS.MATRIX_YEAR_FORECAST,
  MATRIX_SUBJECT_LIMIT: 10,
  /**
   * Вопросы в чате, включённые в разовую покупку Full Matrix.
   * После лимита — обычный тариф QUESTION.
   */
  MATRIX_INCLUDED_QUESTIONS: 3,
  READING: DEFAULT_RUNE_COSTS.READING,
  INTENTION_SPREAD: DEFAULT_RUNE_COSTS.INTENTION_SPREAD,
  QUESTION: DEFAULT_RUNE_COSTS.QUESTION,
  VISION_ANALYSIS: DEFAULT_RUNE_COSTS.VISION_ANALYSIS,
  DAILY_EXTENDED: DEFAULT_RUNE_COSTS.DAILY_EXTENDED,
} as const;

export function numerologySessionCost(): number {
  return PRICING.NUMEROLOGY_SESSION;
}

export function matrixIncludedQuestions(): number {
  return PRICING.MATRIX_INCLUDED_QUESTIONS;
}
